name: Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'   # Only run when a version tag like v1.2.3 is pushed
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ steps.gitversion.outputs.fullSemVer }}

    - name: Pack
      run: dotnet pack --configuration Release --output ./artifacts /p:PackageVersion=${{ steps.gitversion.outputs.fullSemVer }}

    # Remove GitHub Packages source if it already exists
    - name: Remove existing GitHub source (if any)
      run: dotnet nuget remove source github || echo "No existing source to remove"

    # Add GitHub Packages as a NuGet source
    - name: Add GitHub Packages source
      run: dotnet nuget add source `
            --username ${{ github.actor }} `
            --password ${{ secrets.NUGET_AUTH_TOKEN }} `
            --store-password-in-clear-text `
            --name github `
            "https://nuget.pkg.github.com/IT-Beacon/index.json"

    # Push package to GitHub Packages
    - name: Push to GitHub Packages
      run: dotnet nuget push "artifacts/*.nupkg" --source "github" --api-key ${{ secrets.NUGET_AUTH_TOKEN }}