name: Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'   # Only run when a version tag like v1.2.3 is pushed

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Add GitHub Packages as a NuGet source
    - name: Add GitHub Packages source
      run: dotnet nuget add source `
            --username ${{ github.actor }} `
            --password ${{ secrets.NUGET_AUTH_TOKEN }} `
            --store-password-in-clear-text `
            --name github `
            "https://nuget.pkg.github.com/IT-Beacon/index.json"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack --configuration Release --no-build --output artifacts

    # Push package to GitHub Packages
    - name: Push to GitHub Packages
      run: dotnet nuget push "artifacts/*.nupkg" --source "github" --api-key ${{ secrets.NUGET_AUTH_TOKEN }}